#!/bin/bash
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"
echo "${RED} Installing please wait..."
chmod +x ./theme_selector.sh
sudo cp theme_selector.sh /usr/bin/al-theme
echo "${GREEN} Installed. Type al-theme to start"
